Repository enzofrnt/AUTO-QCM, pull requests merged in 2024-10, with the labels that each got.

#147 fix etudiant dashboard
  auto_qcm/app/migrations/0003_alter_reponse_is_correct.py
  auto_qcm/app/templates/dashboard/etudiant_dashboard.html
  auto_qcm/app/views/etudiant_dashboard_view.py
Labels: bug, code, Must

#149 fix
  auto_qcm/app/templates/base.html
  auto_qcm/app/templates/home.html
Labels: bug, Must

#151 Fix login issue150
  auto_qcm/app/templates/base.html
  auto_qcm/app/templates/login.html
Labels: bug, Must

#153 Ajout des test des models pour l'application
  auto_qcm/app/tests/__init__.py
  auto_qcm/app/tests/models/__init__.py
  auto_qcm/app/tests/models/test_plage_model.py
  auto_qcm/app/tests/models/test_qcm_model.py
  auto_qcm/app/tests/models/test_question_model.py
  auto_qcm/app/tests/models/test_reponse_model.py
  auto_qcm/app/tests/models/test_reponseqcm_model.py
  auto_qcm/app/tests/models/test_reponsequestion_model.py
  auto_qcm/app/tests/models/test_tag_model.py
  auto_qcm/app/tests/models/test_utilisateur_model.py
  auto_qcm/app/tests/views/__init__.py
Labels: Must, test

#154 Ajout du premier test des views
  auto_qcm/app/tests/models/test_utilisateur_model.py
  auto_qcm/app/tests/views/test_export_view.py
  auto_qcm/app/views/export_view.py
Labels: bug, Must, test

#155 Changement arborescence des tests
  auto_qcm/app/tests.py
  auto_qcm/app/tests/__init__.py
  auto_qcm/app/tests/apps/models/__init__.py
  auto_qcm/app/tests/apps/models/test_plage_model.py
  auto_qcm/app/tests/apps/models/test_qcm_model.py
  auto_qcm/app/tests/apps/models/test_question_model.py
  auto_qcm/app/tests/apps/models/test_reponse_model.py
  auto_qcm/app/tests/apps/models/test_reponseqcm_model.py
  auto_qcm/app/tests/apps/models/test_reponsequestion_model.py
  auto_qcm/app/tests/apps/models/test_tag_model.py
  auto_qcm/app/tests/apps/models/test_utilisateur_model.py
  auto_qcm/app/tests/apps/views/__init__.py
  auto_qcm/app/tests/apps/views/test_export_view.py
  auto_qcm/app/tests/apps/views/test_search_students_view.py
  auto_qcm/app/tests/models/__init__.py
  auto_qcm/app/tests/views/__init__.py
Labels: Must

#170 Fix plages form
  auto_qcm/app/templates/qcm/qcm_form.html
Labels: bug, code, Must

#171 Ajout test views
  auto_qcm/app/tests/__init__.py
  auto_qcm/app/tests/apps/__init__.py
  auto_qcm/app/tests/apps/models/__init__.py
  auto_qcm/app/tests/apps/views/__init__.py
  auto_qcm/app/tests/apps/views/test_admin_dashboard_view.py
  auto_qcm/app/tests/apps/views/test_change_password_view.py
  auto_qcm/app/tests/apps/views/test_custom_error_view.py
  auto_qcm/app/tests/apps/views/test_delete_multiple_qcms_view.py
  auto_qcm/app/tests/apps/views/test_enseignant_dashboard_view.py
  auto_qcm/app/tests/apps/views/test_etudiant_dashboard_view.py
  auto_qcm/app/tests/apps/views/test_login_view.py
  auto_qcm/app/tests/apps/views/test_qcm_answer_view.py
  auto_qcm/app/tests/apps/views/test_qcm_correction_view.py
  auto_qcm/app/tests/apps/views/test_qcm_create_or_edit_view.py
  auto_qcm/app/tests/apps/views/test_qcm_delete_view.py
  auto_qcm/app/tests/apps/views/test_qcm_list_view.py
  auto_qcm/app/tests/apps/views/test_question_create_or_edit_view.py
  auto_qcm/app/tests/apps/views/test_question_delete_view.py
  auto_qcm/app/tests/apps/views/test_question_list_view.py
  auto_qcm/app/tests/apps/views/test_remove_tags_view.py
  auto_qcm/app/tests/apps/views/test_reponse_qcm_dashboard_view.py
  auto_qcm/app/tests/apps/views/test_save_generated_questions_view.py
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/custom_error_view.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/qcm_acces_view.py
  auto_qcm/auto_qcm/urls.py
Labels: Must, test

#179 Update README.md
  README.md
Labels: documentation, Must
