Repository enzofrnt/AUTO-QCM, pull requests merged in 2024-09, with the labels that each got.

#24 create question to fix issue on dev
  auto_qcm/app/forms.py
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/templates/templatetags/color_filters.py
  auto_qcm/app/views/question_creation_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#49 Ajout du dahsboard et correction des différents bug lié au redirection
  auto_qcm/app/decorators.py
  auto_qcm/app/management/commands/fill_fake_data.py
  auto_qcm/app/mixins.py
  auto_qcm/app/templates/custompermission/403.html
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/custom_permission_denied_view.py
  auto_qcm/app/views/delete_question_view.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/etudiant_dashboard_view.py
  auto_qcm/app/views/export_question_view.py
  auto_qcm/app/views/qcm_creation_view.py
  auto_qcm/app/views/qcm_list_view.py
  auto_qcm/app/views/question_create_or_edit_view.py
  auto_qcm/app/views/question_list_view.py
  auto_qcm/app/views/remove_tags_view.py
  auto_qcm/app/views/search_students_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#76 Ajout formulaire de reponse a un qcm
  auto_qcm/app/migrations/0003_alter_reponseqcm_utilisateur_and_more.py
  auto_qcm/app/models/reponse_question.py
  auto_qcm/app/templates/qcm/qcm_answer.html
  auto_qcm/app/templates/qcm/qcm_correction.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/qcm_answer_view.py
  auto_qcm/app/views/qcm_correction_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#81 Rajout correction des qcm
  auto_qcm/app/forms.py
  auto_qcm/app/migrations/0004_question_melange_rep_question_note.py
  auto_qcm/app/migrations/0005_alter_question_melange_rep.py
  auto_qcm/app/models/question.py
  auto_qcm/app/templates/qcm/qcm_answer.html
  auto_qcm/app/templates/qcm/qcm_correction.html
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/views/qcm_answer_view.py
  auto_qcm/app/views/qcm_correction_view.py
Labels: code, Must

#84 Update enseignant dashboard
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/templates/dashboard/reponse_qcm_dashboard.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/reponse_qcm_dashboard_view.py
  auto_qcm/app/views/search_students_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#85 Create fonction note
  auto_qcm/app/models/reponse_qcm.py
  auto_qcm/app/models/reponse_question.py
  auto_qcm/app/templates/qcm/qcm_correction.html
  auto_qcm/app/views/qcm_correction_view.py
Labels: code, Must

#86 Sprint
  .vscode/settings.json
  auto_qcm/app/decorators.py
  auto_qcm/app/forms.py
  auto_qcm/app/management/commands/fill_fake_data.py
  auto_qcm/app/migrations/0002_remove_eleve_groups_remove_eleve_user_permissions_and_more.py
  auto_qcm/app/migrations/0003_alter_reponseqcm_utilisateur_and_more.py
  auto_qcm/app/migrations/0004_question_melange_rep_question_note.py
  auto_qcm/app/migrations/0005_alter_question_melange_rep.py
  auto_qcm/app/mixins.py
  auto_qcm/app/models/__init__.py
  auto_qcm/app/models/eleve.py
  auto_qcm/app/models/profile.py
  auto_qcm/app/models/question.py
  auto_qcm/app/models/reponse_qcm.py
  auto_qcm/app/models/reponse_question.py
  auto_qcm/app/models/user.py
  auto_qcm/app/templates/base.html
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/templates/dashboard/reponse_qcm_dashboard.html
  auto_qcm/app/templates/pp.html
  auto_qcm/app/templates/qcm/qcm_answer.html
  auto_qcm/app/templates/qcm/qcm_correction.html
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/templates/qcm/qcm_list.html
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/qcm_answer_view.py
  auto_qcm/app/views/qcm_correction_view.py
  auto_qcm/app/views/question_generation_view.py
  auto_qcm/app/views/reponse_qcm_dashboard_view.py
  auto_qcm/app/views/save_generated_questions_view.py
  auto_qcm/app/views/search_students_view.py
  auto_qcm/auto_qcm/settings/base.py
  auto_qcm/auto_qcm/urls.py
  deploiement-dev/.env
  deploiement-prod/.env
  requirements.txt
Labels: code, Must

#88 Dashbord etudiant
  auto_qcm/app/management/commands/fill_fake_data.py
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/templates/dashboard/etudiant_dashboard.html
  auto_qcm/app/templates/support_doc/support_doc.html
  auto_qcm/app/views/etudiant_dashboard_view.py
  auto_qcm/app/views/qcm_correction_view.py
Labels: code, Must

#91 Fix bug export
  auto_qcm/app/models/question.py
Labels: code, Must

#92 Fix bug calendar enseignant dashboard
  auto_qcm/app/decorators.py
  auto_qcm/app/mixins.py
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/views/etudiant_dashboard_view.py
  auto_qcm/app/views/qcm_correction_view.py
Labels: bug, Must

#93 Update creer question et supprimer pour renvoyer sur la page d'avant
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/views/delete_question_view.py
  auto_qcm/app/views/question_create_or_edit_view.py
Labels: code, Must

#100 Dashbord etudiant
  auto_qcm/app/management/commands/fill_fake_data.py
  auto_qcm/app/templates/dashboard/etudiant_dashboard.html
  auto_qcm/app/views/etudiant_dashboard_view.py
Labels: code, Must

#102 Update enseignant dashboard stats
  auto_qcm/app/models/question.py
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/templates/dashboard/qcm_statistics.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/qcm_statistique_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#106 Ajout d'une nouvelle font
  auto_qcm/app/static/css/style.css
  auto_qcm/app/templates/base.html
  auto_qcm/auto_qcm/urls.py
Labels: code, Should

#108 Fix login
  auto_qcm/app/mixins.py
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/delete_qcm_view.py
  auto_qcm/app/views/delete_question_view.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/etudiant_dashboard_view.py
  auto_qcm/app/views/export_view.py
  auto_qcm/app/views/home_view.py
  auto_qcm/app/views/qcm_answer_view.py
  auto_qcm/app/views/qcm_correction_view.py
  auto_qcm/app/views/qcm_create_or_edit_view.py
  auto_qcm/app/views/qcm_creation_view.py
  auto_qcm/app/views/qcm_statistique_view.py
  auto_qcm/app/views/question_create_or_edit_view.py
  auto_qcm/app/views/question_creation_view.py
  auto_qcm/app/views/remove_tags_view.py
  auto_qcm/app/views/reponse_qcm_dashboard_view.py
  auto_qcm/app/views/save_generated_questions_view.py
  auto_qcm/app/views/search_students_view.py
  auto_qcm/app/views/support_doc_view.py
Labels: bug, Must

#110 Ajout page erreur 404 et 500
  auto_qcm/app/templates/errors/403.html
  auto_qcm/app/templates/errors/404.html
  auto_qcm/app/templates/errors/500.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/custom_error_view.py
  auto_qcm/app/views/custom_permission_denied_view.py
  auto_qcm/auto_qcm/urls.py
Labels: bug, code, Must

#112 Fix login
  auto_qcm/app/templates/login/login.html
Labels: bug, Must

#113 Plages qcm
  auto_qcm/app/admin.py
  auto_qcm/app/decorators.py
  auto_qcm/app/forms.py
  auto_qcm/app/management/commands/fill_fake_data.py
  auto_qcm/app/migrations/0001_initial.py
  auto_qcm/app/migrations/0002_remove_eleve_groups_remove_eleve_user_permissions_and_more.py
  auto_qcm/app/migrations/0003_alter_reponseqcm_utilisateur_and_more.py
  auto_qcm/app/migrations/0004_question_melange_rep_question_note.py
  auto_qcm/app/migrations/0005_alter_question_melange_rep.py
  auto_qcm/app/mixins.py
  auto_qcm/app/models/__init__.py
  auto_qcm/app/models/plage.py
  auto_qcm/app/models/qcm.py
  auto_qcm/app/models/question.py
  auto_qcm/app/models/reponse.py
  auto_qcm/app/models/reponse_qcm.py
  auto_qcm/app/models/reponse_question.py
  auto_qcm/app/models/user.py
  auto_qcm/app/models/utilisateur.py
  auto_qcm/app/static/css/pp_style.css
  auto_qcm/app/templates/base.html
  auto_qcm/app/templates/pp.html
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/enseignant_dashboard_view.py
  auto_qcm/app/views/etudiant_dashboard_view.py
  auto_qcm/app/views/qcm_create_or_edit_view.py
  auto_qcm/app/views/qcm_creation_view.py
  auto_qcm/app/views/qcm_delete_view.py
  auto_qcm/app/views/question_delete_view.py
  auto_qcm/app/views/search_students_view.py
  auto_qcm/auto_qcm/settings/base.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Must

#117 fix-bug et update front
  auto_qcm/app/templates/base.html
  auto_qcm/app/templates/dashboard/etudiant_dashboard.html
  auto_qcm/app/views/etudiant_dashboard_view.py
Labels: bug, code, Must

#125 Ajout des plages pour le calendrier et fix bug de search_students
  auto_qcm/app/migrations/0002_alter_plage_groupe_alter_plage_promo.py
  auto_qcm/app/models/plage.py
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/views/search_students_view.py
Labels: bug, code, Must

#124 Fix erreurs forms
  auto_qcm/app/forms.py
  auto_qcm/app/models/reponse.py
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/views/qcm_create_or_edit_view.py
  auto_qcm/app/views/question_create_or_edit_view.py
  auto_qcm/app/views/question_creation_view.py
Labels: bug, code, Must

#135 Bug fix
  auto_qcm/app/templates/base.html
Labels: bug, Must

#136 Bug fix
  auto_qcm/app/templates/dashboard/qcm_statistics.html
  auto_qcm/app/views/qcm_statistique_view.py
Labels: bug, Must

#139 Bug fix
  auto_qcm/app/templates/qcm/qcm_form.html
Labels: bug, Must
