Repository enzofrnt/AUTO-QCM, pull requests merged in 2024-11, with the labels that each got.

#201 Ajout filtre calendrier
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/views/enseignant_dashboard_view.py
Labels: bug, code, Must

#203 fix du login qui était pas au centre
  auto_qcm/app/static/css/login_style.css
  auto_qcm/app/templates/base.html
Labels: bug, Must

#223 Ajout du filtre pour les qcm pour filtrer par année
  auto_qcm/app/migrations/0003_qcm_date_creation.py
  auto_qcm/app/models/qcm.py
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
  auto_qcm/app/views/enseignant_dashboard_view.py
Labels: code, Must

#226 Ajout des lien cliquables vers le edit du qcm dans enseignant dashboard
  auto_qcm/app/templates/dashboard/enseignant_dashboard.html
Labels: code, Should

#228 Ajout de l'infobulle pour l'explication du latex
  auto_qcm/app/templates/questions/question_form.html
Labels: code, Must

#237 Export amc txt et amélioration de l'export
  auto_qcm/app/models/qcm.py
  auto_qcm/app/models/question.py
  auto_qcm/app/templates/qcm/qcm_list.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/export_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Should

#239 Ajout d'une image à une question
  .gitignore
  auto_qcm/app/forms.py
  auto_qcm/app/migrations/0004_question_image.py
  auto_qcm/app/models/question.py
  auto_qcm/app/templates/qcm/qcm_answer.html
  auto_qcm/app/templates/questions/question_display.html
  auto_qcm/app/templates/questions/question_form.html
  auto_qcm/app/views/qcm_acces_view.py
  auto_qcm/app/views/question_create_or_edit_view.py
  auto_qcm/auto_qcm/settings/base.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Should

#246 fix ajout image lors de la correction
  auto_qcm/app/templates/qcm/qcm_correction.html
  auto_qcm/app/templates/questions/question_display.html
Labels: bug, code, Must

#250 Ajout bouton pour supprimer les tags
  auto_qcm/app/templates/questions/question_filter_form.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/delete_tag_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code

#256 Fix selection des qcm
  auto_qcm/app/templates/qcm/qcm_list.html
Labels: bug, Must

#258 Renamed nbreponses to nb tentatives
  auto_qcm/app/forms.py
  auto_qcm/app/migrations/0005_rename_nb_reponses_qcm_nb_tentatives.py
  auto_qcm/app/models/qcm.py
  auto_qcm/app/templates/qcm/qcm_acces.html
  auto_qcm/app/templates/qcm/qcm_form.html
  auto_qcm/app/tests/apps/views/test_qcm_create_or_edit_view.py
Labels: bug, code, Must

#260 Duplication de question possible
  auto_qcm/app/static/js/questions/question_events.js
  auto_qcm/app/templates/questions/question_display.html
  auto_qcm/app/views/__init__.py
  auto_qcm/app/views/question_duplicate_view.py
  auto_qcm/auto_qcm/urls.py
Labels: code, Should

#265 Rajout sprint 5 dans le readme
  README.md
Labels: Must, Tache
